apiVersion: v1
kind: Service
metadata:
  name: cloud4future-node-svc
  namespace: app
  labels:
    app: cloud4future-node
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: cloud4future-node
  ports:
    - name: http
      port: 80
      targetPort: 3000
